### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by shawnwiggins** [ccsf-math-108/materials-sp24#2]
A few people were mentioning that the keyboard shortcuts like `a` and `b` for adding new code cells were not working. I see that this is an issue with Jupyter Notebooks and it is being talked about on [their GitHub issues page](https://github.com/jupyter/notebook/issues/7241). I'll follow their commentary for an update and then implement that fix as soon as there is one. In the meantime, it looks like you might need to add cells without using a shortcut.

**Comment by futbol4me** [comment]
seems like jupyter notebook vs lab work differently.... notebook has A (insert above) and B shortcuts disabled...

<img width="565" alt="image" src="https://github.com/ccsf-math-108/materials-sp24/assets/8358816/824fbcf4-f625-4193-b40d-9cb721d462d5">


yet these options appear in the menu when you use the jupyterlab interface.  this bug appears in both windows and mac.

<img width="585" alt="image" src="https://github.com/ccsf-math-108/materials-sp24/assets/8358816/3f669dec-8686-4900-87da-ea98e6252bbb">

**Comment by futbol4me** [comment]
im finding A, B and DD shortcuts disabled on notebook (on windows and mac) but work when opening via jupyterlab interface

**Comment by shawnwiggins** [comment]
@futbol4me 
> im finding A, B and DD shortcuts disabled on notebook (on windows and mac) but work when opening via jupyterlab interface

Yeah, one of the core developers for Notebooks just wrote:

> Thanks all for the report.
>
> Wondering if this could be related to the recent JupyterLab 4.1.0 release, which may have introduced some incompatibility with the Notebook settings (in particular the keyboard shortcuts).
>
> As a temporary workaround, does downgrading to the previous JupyterLab version (with pip install "jupyterlab<4.1.0") help fix the issue?

Since Notebooks are built on Lab, it sounds like they will be able to fix the issue soon. I'll keep an eye out for that patch and I'll apply it as soon as it is available.  Since JupyterLab 4.1.0 included accessibility improvements, I want to keep using it. (For legal and personal reasons, accessibility goals are higher than the availability of shortcuts.)

**Comment by shawnwiggins** [comment]
@futbol4me, I made an update based on their recommendation. Will you go to your [hub panel](https://ccsf.cloudbank.2i2c.cloud/hub/home), click **Stop My Server**, wait a few seconds for the screen to change, click **Start Server**, and then open a notebook to see if they shortcuts are back for you?

**Comment by shawnwiggins** [comment]
It seems good now.
