### ISSUE TITLE
HW5 task 4: add results to table... but what name should we call the column?

### ISSUE THREAD

**Issue by futbol4me** [ccsf-math-108/materials-sp24#8]
<img width="971" alt="image" src="https://github.com/ccsf-math-108/materials-sp24/assets/8358816/950509c0-6310-46d6-a2ee-d5b30c0e8ed3">

should we specify the label of the column assigned to the array we are adding to the table?

**Comment by shawnwiggins** [comment]
Good question, @futbol4me. Currently, we are not checking the column label for the column that is added, so use any label you want for that column.

_I'll leave this open until the assignment deadline._
